[package]
name = "pdf-writer"
version = "0.1.0"
authors = ["Ian van de Poll <ian.vd.poll@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
